const STRINGS = {
    appName: 'Dhoomak',
    chooseByCategories: 'Choose by Categories',
    itemName: "Item name",
    category: "Category",
    quanity: "Quantity",
    addItems: "Add Items",
    enterNumberAndLogin: "Enter Mobile Number and Login",
    enterOtp: "Send OTP",
    loginTextPlaceholder: "Enter your number",
    enterOtpAndVerify: "Please enter the OTP sent to your number",
    enterOtpAndVerifyExecutive: "OTP has been sent to",
    verifyOtp: "Verify OTP",
    inventoryCompleted: "Your Inventory is completed",
    comingSoon: 'Coming Soon!!',
    launchingSoon: 'Launching Soon!!',
    productDescription: 'Product Description',
    importantInformation: 'Important Information',
    information: 'Information',
    rupeeSign: '₹',
    add: 'Add',
    remove: 'Remove',
    readMore: 'Read More',
    readLess: 'Read Less',
};

export default STRINGS;